### ISSUE TITLE
Autosave

### ISSUE THREAD

**Issue by polynomialherder** [gwgundersen/anno#16]
Thanks so much for working on this and open sourcing it -- I've been hungry for something like Overleaf but self-hosted and open-source, and this has really hit the spot for me. 

Is autosave by any chance on the roadmap? I accidentally close browser tabs all the time, which with anno can lead to work lost which is always a bummer.

Another thing that was a little confusing to me at first was that to trigger a manual save while editing, we need to click the `Edit text` button -- do you think it might make sense to change the button text to `Save text`?

I'm happy to help with these issues if you think they're worthwhile (I'm also happy to fork my own and patch locally if there's tension between these suggestions and your own workflow).

**Comment by gwgundersen** [comment]
I'm glad you're finding it useful!

1. I hadn't thought about autosave, but I think it's a good idea. Long term, I think a configuration file (see https://github.com/gwgundersen/anno/issues/9) would be nice, but for now a sensible default is fine. It looks like Juypter notebook's default is 120 seconds.

2. I agree with `Save text` being better. Just `Save` even?

3. It would also be nice to bind `CTRL+S` to save a la Jupyter notebooks. It looks like binding `CTRL+S` is straightforward: https://stackoverflow.com/a/14180949/1830334. I'm on the fence about using jQuery (https://github.com/gwgundersen/anno/issues/4), and my preference is to avoid using it when possible. Ideally, Anno should have as few dependencies as possible in the spirit of a staying a small, one-purpose tool.

I'd love a PR with any of these changes. Just LMK what you have bandwidth for so I don't double up the work.

**Comment by gwgundersen** [comment]
@affinespaces, this is in master if you want to build from source and use (see README). I'm not sure when v0.0.3 will go out. Feel free to report any auto-save issues here if you see anything, and I'll close when I get around to releasing.
